Implemented recovered deleted wabinar
ms-club-sliit/msclub-backend pull request #163
Opened 2022-01-14 12:31 UTC by dilafar

2022-01-14 13:41 UTC, rusiruavb requested changes

2022-01-14 13:41 UTC, rusiruavb commented on src/api/services/Webinar.service.ts
> +			}
The if condition should handle like this.
```
if (webinarDetails) {
   if (webinarDetails !== null) {
      // Implement the recover logic here
   } else {
      return "Webinar is already recovered";
   }
} else {
   return "Webinar not found";
}
```

2022-01-17 04:17 UTC, rusiruavb commented
@dilafar please resolve the conflicts

2022-01-18 11:01 UTC, senuravihanjayadeva approved these changes

2022-01-18 14:53 UTC, rusiruavb approved these changes

2022-01-18 14:54 UTC, merged