Recover deleted application added
ms-club-sliit/msclub-backend pull request #164
Opened 2022-01-15 03:33 UTC by uihalagedara

2022-01-15 03:43 UTC, senuravihanjayadeva requested changes

2022-01-15 03:43 UTC, senuravihanjayadeva commented on src/api/controllers/Application.controller.ts
> +	await ApplicationService.recoverDeletedApplication(request.body.applicationId)
request.body.applicationId should be checked null or not in the controller

2022-01-15 20:52 UTC, miyurugunarathna approved these changes
LGTM

2022-01-16 05:08 UTC, rusiruavb requested changes
@uihalagedara I have request some changes from your code. Please take a look.

2022-01-16 05:08 UTC, rusiruavb commented on src/api/services/Application.service.ts
> +				}
If there is no application in the else part `throw new Error("Application is not found");`

2022-01-16 05:08 UTC, rusiruavb commented on src/api/services/Application.service.ts
> +						return application.save();
This should be `return await application.save()`

2022-01-17 04:13 UTC, senuravihanjayadeva approved these changes

2022-01-17 04:14 UTC, senuravihanjayadeva approved these changes

2022-01-17 04:14 UTC, merged