Add recover deleted user function
ms-club-sliit/msclub-backend pull request #171
Opened 2022-01-18 09:54 UTC by SDSamarasinghe

2022-01-18 14:52 UTC, rusiruavb requested changes

2022-01-18 14:52 UTC, rusiruavb commented on src/api/services/TopSpeaker.service.ts
> +				topSpeakerDetails.deletedBy = null as any;
Is there any specific reason to use `any` in here?

2022-01-18 14:52 UTC, rusiruavb commented on src/api/services/TopSpeaker.service.ts
> +				return null;
Do not return `null` to the controller. Add this to `else` part,
```
const errorData = {
   message: "Top speaker information not found",
   dateTime: new Date()
};

throw new Error(JSON.stringify(errorData));
```

2022-01-18 14:52 UTC, rusiruavb commented on src/api/controllers/TopSpeaker.controller.ts
> +		request.handleResponse.errorRespond(response)("Top Speaker ID not found");
Add `next()` function after handle the response.
```
request.handleResponse.errorRespond(response)("Top Speaker ID not found");
next();
```

2022-01-18 14:56 UTC, rusiruavb commented
There is a conflict in the `package-lock.json` file. Please resolve and update the PR.

2022-01-19 12:48 UTC, senuravihanjayadeva requested changes

2022-01-19 12:48 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +				topSpeakerDetails.deletedBy = null as any;
Change it in the interface machn. Reffer Event Interface

2022-01-19 13:44 UTC, rusiruavb requested changes
@SDSamarasinghe I add small comment. Please take a look

2022-01-19 13:44 UTC, rusiruavb commented on src/api/controllers/TopSpeaker.controller.ts
> +		request.handleResponse.errorRespond(response)("Top Speaker ID not found");
Add date and time to the response.
```
request.handleResponse.errorRespond(response)({ message: "Top Speaker ID not found", dateTime: new Date() });
next();
```

2022-01-22 02:41 UTC, senuravihanjayadeva requested changes

2022-01-22 02:41 UTC, senuravihanjayadeva commented on src/api/routes/index.ts
> +  app.get("/admin/topspeaker/recover/", middleware.authenticate, controller.recoverDeletedTopSpeaker);
this should be a "put" request not "get"

2022-01-22 08:03 UTC, SDSamarasinghe commented on src/api/routes/index.ts
> +  app.get("/admin/topspeaker/recover/", middleware.authenticate, controller.recoverDeletedTopSpeaker);
but aiye.. delete function also has a get method neda?

2022-01-22 09:42 UTC, senuravihanjayadeva approved these changes

2022-01-22 09:43 UTC, merged