Implemented fetch deleted contactUs
ms-club-sliit/msclub-backend pull request #173
Opened 2022-01-25 06:02 UTC by ThaminduChankana

2022-01-25 10:14 UTC, miyurugunarathna requested changes

2022-01-25 10:14 UTC, miyurugunarathna commented on src/api/services/Contact.service.ts
> +	return await ContactModel.find({ deletedAt: { $ne: null } })
This should be ContactModel.aggregate([{ $match: { deletedAt: { $ne: null } } }])

2022-01-25 13:22 UTC, miyurugunarathna approved these changes
LGTM

2022-01-27 14:47 UTC, senuravihanjayadeva approved these changes

2022-01-27 14:47 UTC, merged