Delete webinar permanantly
ms-club-sliit/msclub-backend pull request #186
Opened 2022-02-06 17:59 UTC by ChathurikaThathsarani

2022-02-06 19:00 UTC, senuravihanjayadeva requested changes

2022-02-06 19:00 UTC, senuravihanjayadeva commented on src/api/controllers/Webinar.controller.ts
> +	await WebinarService.deleteWebinarPermanently(request.body.webinarId)
check first request.body.webinarId is existing or not

2022-02-06 19:37 UTC, miyurugunarathna requested changes

2022-02-06 19:37 UTC, miyurugunarathna commented on src/api/services/index.ts
>  	//@todo import deleteWebinarPermanently method
Remove this todo.

2022-02-06 19:37 UTC, miyurugunarathna commented on src/api/services/index.ts
>  	//@todo export deleteWebinarPermanently method
Remove this todo.

2022-02-06 19:37 UTC, miyurugunarathna commented on src/api/services/Webinar.service.ts
> +export const deleteWebinarPermanently = async (webinarId: string) => {
Use async await properly to this function.

2022-02-07 04:05 UTC, senuravihanjayadeva requested changes

2022-02-07 04:05 UTC, senuravihanjayadeva commented on src/api/services/Webinar.service.ts
> +		return WebinarModel.findByIdAndDelete(webinarId)
use await here

2022-02-07 04:05 UTC, senuravihanjayadeva commented on src/interfaces/IWebinar.ts
> +export type { IWebinar, IUpdatedBy };
No need to exported IUpdatedBy here.  Exporting IWebinar is enough

2022-02-07 10:36 UTC, senuravihanjayadeva requested changes

2022-02-07 10:36 UTC, senuravihanjayadeva commented on src/api/services/index.ts
>  	//@todo export deleteWebinarPermanently method
Remove this todo.

2022-02-07 10:39 UTC, senuravihanjayadeva requested changes

2022-02-07 10:39 UTC, senuravihanjayadeva commented on src/api/controllers/Webinar.controller.ts
> +		await WebinarService.deleteWebinarPermanently(request.body.webinarId)
use webinarId instead request.body.webinarId

2022-02-07 11:16 UTC, KaveenLaksitha approved these changes

2022-02-07 11:19 UTC, KaveenLaksitha approved these changes

2022-02-07 11:23 UTC, merged