Delete application from the databse
ms-club-sliit/msclub-backend pull request #190
Opened 2022-02-07 18:20 UTC by SasinduNanayakkara

2022-02-08 09:31 UTC, senuravihanjayadeva requested changes

2022-02-08 09:31 UTC, senuravihanjayadeva commented on src/api/controllers/Application.controller.ts
> +//import { error } from "console";
Please remove this line if unwanted

2022-02-08 09:31 UTC, senuravihanjayadeva commented on src/api/controllers/Application.controller.ts
> +//import { request } from "http";
Please remove this line if unwanted

2022-02-08 14:31 UTC, miyurugunarathna approved these changes
LGTM

2022-02-09 10:58 UTC, senuravihanjayadeva approved these changes

2022-02-09 10:59 UTC, merged