Implemented Remove Inquries permanently from the database
ms-club-sliit/msclub-backend pull request #198
Opened 2022-02-11 14:00 UTC by isurupathumherath

2022-02-11 17:10 UTC, senuravihanjayadeva requested changes

2022-02-11 17:10 UTC, senuravihanjayadeva commented on package.json
> +		"start": "NODE_ENV=Production node build/app.js",
change Production into Development

2022-02-11 17:10 UTC, senuravihanjayadeva commented on src/api/controllers/Contact.controller.ts
> +	await ContactService.deleteContactPermanently(request.body.contactId)
Take the contactId as the url parameter

2022-02-11 19:09 UTC, isurupathumherath commented
Required Changes are done

2022-02-12 03:32 UTC, senuravihanjayadeva approved these changes

2022-02-12 03:32 UTC, merged