Delete internal meetings permanently.
ms-club-sliit/msclub-backend pull request #236
Opened 2022-04-15 06:44 UTC by SDSamarasinghe

2022-04-15 07:16 UTC, SDSamarasinghe commented
[https://github.com/ms-club-sliit/msclub-backend/issues/230#issue-1203091121](url)

2022-04-15 07:34 UTC, senuravihanjayadeva requested changes

2022-04-15 07:34 UTC, senuravihanjayadeva commented on package.json
> +		"start": "NODE_ENV=Production node build/app.js",
This should be Development

2022-04-15 07:48 UTC, SDSamarasinghe commented on package.json
> +		"start": "NODE_ENV=Production node build/app.js",
Done

2022-04-15 11:54 UTC, ThusharaX requested changes

2022-04-15 11:54 UTC, ThusharaX commented on src/api/services/Meeting.service.ts
> +	const meetings = await MeetingModel.findById(meetingId);
This should be a `meeting`, since we delete only one meeting, right?

2022-04-16 01:45 UTC, SDSamarasinghe commented on src/api/services/Meeting.service.ts
> +	const meetings = await MeetingModel.findById(meetingId);
done

2022-04-16 06:30 UTC, ThusharaX approved these changes
LGTM

2022-04-16 07:10 UTC, senuravihanjayadeva requested changes

2022-04-16 07:10 UTC, senuravihanjayadeva commented on src/api/services/Meeting.service.ts
> +					.then((meeting) => {
change this otherwise others will confuse. having same name for Meeting model and inside then.
change deletedMeeting instead of meeting

2022-04-17 02:20 UTC, senuravihanjayadeva approved these changes

2022-04-17 02:38 UTC, merged