Create Top Speaker Model #21
ms-club-sliit/msclub-backend pull request #24
Opened 2021-11-25 17:57 UTC by MadhushaPrasad

2021-11-25 18:05 UTC, senuravihanjayadeva requested changes

2021-11-25 18:05 UTC, senuravihanjayadeva commented on src/api/interfaces/ITopSpeaker.ts
> +interface ITopSpeakerMedia {
https://github.com/ms-club-sliit/msclubwesite-v2/blob/master/src/data/TopSpeakersData.json

Please Consider above stucture for social Medias

2021-11-25 18:05 UTC, senuravihanjayadeva commented on src/api/interfaces/ITopSpeaker.ts
> +interface ITopSpeaker extends Document {
Please use the following attribute names when naming 
https://github.com/ms-club-sliit/msclubwesite-v2/blob/master/src/data/TopSpeakersData.json

2021-11-25 18:19 UTC, rusiruavb requested changes
I have add some comments. Please take a look

2021-11-25 18:19 UTC, rusiruavb commented on src/api/models/TopSpeaker.model.ts
> +  isDelete: { type: Boolean, required: true, default: false },
change `isDelete` to `deletedAt` and the data type should be `Date`. 
`deletedAt: { type: Date, required: fasle, default: null }` 
When we get the speaker information just check whether `deletedAt` field is null or not. `null` means its not deleted.

2021-11-25 18:20 UTC, rusiruavb commented
@MadhushaPrasad please resolve the conflicts

2021-11-25 18:25 UTC, senuravihanjayadeva commented on src/api/models/TopSpeaker.model.ts
> +  isDelete: { type: Boolean, required: true, default: false },
I though we are using a boolean status. In that case Event modal also should updated.

2021-11-26 04:51 UTC, rusiruavb requested changes
change `isDelete` to `deletedAt` and the data type should be `Date`. 
`deletedAt: { type: Date, required: fasle, default: null }` 
When we get the speaker information just check whether `deletedAt` field is null or not. `null` means its not deleted.

2021-11-26 04:51 UTC, rusiruavb commented on src/api/models/TopSpeaker.model.ts
> +  isDelete: { type: Boolean, required: true, default: false },
Normally we use date time to track the deleted time. That's why I suggested to use `Date` for deletedAt.

2021-11-26 05:50 UTC, senuravihanjayadeva commented
please resolve the conflicts @MadhushaPrasad

2021-11-27 02:16 UTC, senuravihanjayadeva requested changes

2021-11-27 02:16 UTC, senuravihanjayadeva commented on src/api/interfaces/ITopSpeaker.ts
> +interface ITopSpeaker extends Document {
Please Consider attribute names according to the above json File 

    {
      "id": 1,
      "imageUrl": "/assets/speakers/Fiqri-Ismail.jpg",
      "title": "Fiqri Ismail",
      "description": "Architect . Author . Teacher . MVP - Azure",
      "socialMediaURLs": {
        "facebook": "https://www.facebook.com/fiqri.ismail",
        "instagram": "https://www.instagram.com/fiqriismail/",
        "twitter": "https://twitter.com/fiqriismail",
        "linkedIn": "https://www.linkedin.com/pub/fiqri-ismail/29/b75/122",
        "web": "https://askfiqri.com/"
      }

2021-11-27 02:16 UTC, senuravihanjayadeva commented on src/api/interfaces/ITopSpeaker.ts
> +  deletedAt?: string;
deletedAt datatype should be Date

2021-11-27 02:16 UTC, senuravihanjayadeva commented on src/api/interfaces/ITopSpeaker.ts
> +  socialMedia: ITopSpeakerMedia[];
ITopSpeakerMedia not ITopSpeakerMedia[]

2021-11-27 02:16 UTC, senuravihanjayadeva commented on src/api/interfaces/ITopSpeaker.ts
> +  socialMedia: ITopSpeakerMedia[];
socialMediaURLs instead of socialMedia

2021-11-27 02:16 UTC, senuravihanjayadeva commented on src/api/models/TopSpeaker.model.ts
> +const TopSpeakerSchema = new Schema<ITopSpeaker>({
Please use the above schema

2021-11-27 02:21 UTC, senuravihanjayadeva commented on src/api/interfaces/ITopSpeaker.ts
> +  deletedAt?: string;
https://github.com/ms-club-sliit/msclubwesite-v2/blob/master/src/data/TopSpeakersData.json

consider the following schema when naming attribute

2021-11-27 05:27 UTC, rusiruavb requested changes
Make the changes that @senuravihanjayadeva have requested.

2021-11-27 19:07 UTC, closed without merging