BoardMember Services added
ms-club-sliit/msclub-backend pull request #45
Opened 2021-11-26 17:11 UTC by nisalrenuja

2021-11-26 17:55 UTC, senuravihanjayadeva requested changes

2021-11-26 17:55 UTC, senuravihanjayadeva commented on src/api/services/BoardMember.service.ts
> +        return await boardMemberDetails.save();
should be updated deletedAt attribute

2021-11-26 17:58 UTC, senuravihanjayadeva commented on src/api/services/BoardMember.service.ts
> +        return await boardMemberDetails.save();
In the IBoardMember and IExecutiveBoard interfaces deletedAt attribute is missing. Please add that also. ( Also add those to the BoardMember and ExecutiveBoard Models ) You can refer IEvent interface and Event Model.

2021-11-27 05:38 UTC, rusiruavb requested changes
Make the changes that @senuravihanjayadeva have made.

2021-11-27 05:43 UTC, nisalrenuja commented
> Make the changes that @senuravihanjayadeva have made.

I did the changes that @senuravihanjayadeva have requested

2021-11-27 08:40 UTC, senuravihanjayadeva approved these changes

2021-11-27 09:28 UTC, merged