Feature/top speaker controller
ms-club-sliit/msclub-backend pull request #53
Opened 2021-11-28 16:47 UTC by ShivaaniDushya

Completed the issues.
1. Add Top Speaker Routes
2. Create Top Speaker Controllers

2021-11-28 17:01 UTC, senuravihanjayadeva requested changes

2021-11-28 17:01 UTC, senuravihanjayadeva commented on src/api/routes/index.ts
> +  app.get("/topspeaker/", controller.getTopSpeakers);
same routes for both getTopSpeaker and getTopSpeakers. Please put topSpeakerId for getTopSpeaker route

2021-11-29 04:05 UTC, senuravihanjayadeva requested changes

2021-11-29 04:05 UTC, senuravihanjayadeva commented on src/api/routes/index.ts
> +  app.get("/topspeaker/:topspeakerId/", controller.getTopSpeaker);
it should be topSpeakerId. Should be Camel case. not topspeakerId

2021-11-29 04:05 UTC, senuravihanjayadeva commented on src/api/routes/index.ts
> +  app.put("/topspeaker/:topspeakerId", controller.updateTopSpeaker);
it should be topSpeakerId. Should be Camel case. not topspeakerId

2021-11-29 04:05 UTC, senuravihanjayadeva commented on src/api/routes/index.ts
> +  app.put("/topspeaker/delete/:topspeakerId", controller.deleteTopSpeaker);
it should be topSpeakerId. Should be Camel case. not topspeakerId

2021-11-29 04:45 UTC, rusiruavb requested changes

2021-11-29 04:45 UTC, rusiruavb commented on src/api/controllers/TopSpeaker.controller.ts
>   * @todo implement a @function insertTopSpeaker that calls
Remove the `@todo` and add proper comment for the function.
```
/**
 * @param {IContact} contactData
 * @returns {IContact} Contact data
 */
```

2021-11-29 04:45 UTC, rusiruavb commented on src/api/controllers/TopSpeaker.controller.ts
> +    await TopSpeakerService.getTopSpeaker(request.params.topSpeakerId)
Before `topSpeaker` is pass to the `getTopSpeaker` function, first assign `topSpeakerId` to a variable and check if the variable value is empty or not. If it is not null then pass as the parameter, otherwise send an error response.
```
let topSpeakerId = request.params.topSpeakerId;

if (topSpeakerId) {
   // call the service function
} else {
   request.handleResponse.errorRespond(response)('Top Speaker ID not found');
}
```

2021-11-29 04:45 UTC, rusiruavb commented on src/api/controllers/TopSpeaker.controller.ts
> +    await TopSpeakerService.updateTopSpeaker(request.params.topSpeakerId, request.body)
Before `topSpeaker` is pass to the `updateTopSpeaker` function, first assign `topSpeakerId` to a variable and check if the variable value is empty or not. If it is not null then pass as the parameter, otherwise send an error response.
```
let topSpeakerId = request.params.topSpeakerId;

if (topSpeakerId) {
   // call the service function
} else {
   request.handleResponse.errorRespond(response)('Top Speaker ID not found');
}
```

2021-11-29 04:45 UTC, rusiruavb commented on src/api/controllers/TopSpeaker.controller.ts
> +    await TopSpeakerService.deleteTopSpeaker(request.params.topSpeakerId)
Before `topSpeaker` is pass to the `deleteTopSpeaker` function, first assign `topSpeakerId` to a variable and check if the variable value is empty or not. If it is not null then pass as the parameter, otherwise send an error response.
```
let topSpeakerId = request.params.topSpeakerId;

if (topSpeakerId) {
   // call the service function
} else {
   request.handleResponse.errorRespond(response)('Top Speaker ID not found');
}
```

2021-11-29 04:46 UTC, rusiruavb commented
@ShivaaniDushya resolve the conflict

2021-11-29 08:49 UTC, senuravihanjayadeva commented
Please resolve conflicts

2021-11-29 09:10 UTC, senuravihanjayadeva approved these changes

2021-11-29 09:11 UTC, merged