Application Service Created
ms-club-sliit/msclub-backend pull request #56
Opened 2021-11-28 18:17 UTC by AshenWijesingha

2021-11-28 18:56 UTC, senuravihanjayadeva requested changes

2021-11-28 18:56 UTC, senuravihanjayadeva commented on src/api/services/Application.service.ts
> +    return await ApplicationModel.find()
soft deleted ones shouldnt be displayed. Please filter those soft deleted data. You can use match method for this

2021-11-28 18:56 UTC, senuravihanjayadeva commented on src/api/services/Application.service.ts
> +    return await ApplicationModel.findByIdAndDelete(applicationId)
Please refer delete method in event service. Here we are updating only deletedAt attribute. Not a hard delete

2021-11-28 18:59 UTC, AshenWijesingha commented on src/api/services/Application.service.ts
> +    return await ApplicationModel.find()
ok ayye

2021-11-28 19:10 UTC, AshenWijesingha commented on src/api/services/Application.service.ts
> +    return await ApplicationModel.findByIdAndDelete(applicationId)
Done ayye

2021-11-28 19:20 UTC, senuravihanjayadeva requested changes

2021-11-28 19:20 UTC, senuravihanjayadeva commented on src/api/services/Application.service.ts
> +export const fetchApplications = async (filter: FilterQuery<IApplication>) => {
for fliter data which is deletedAt = null refer mongoose documentation
https://mongoosejs.com/docs/api.html#model_Model.find
ex :  MyModel.find({ name: 'john'} )

2021-11-28 19:20 UTC, senuravihanjayadeva commented on src/api/services/Application.service.ts
> +export const fetchApplications = async (filter: FilterQuery<IApplication>) => {
remove filter in line 35 and 36

2021-11-29 04:34 UTC, rusiruavb requested changes

2021-11-29 04:34 UTC, rusiruavb commented on src/api/services/Application.service.ts
>   * @todo create @function addApplication to save an Application in the database
Remove the `@todo` and add proper comment for the function.
```
/**
 * @param {IContact} applicationData
 * @returns {IContact} Application document
 */
```

2021-11-29 04:34 UTC, rusiruavb commented on src/api/services/Application.service.ts
> +    .then(async (application) => {
No need to have `async` in here. Remove the `async` keyword

2021-11-29 04:34 UTC, rusiruavb commented on src/api/services/Application.service.ts
> +    .then(async (application) => {
No need to have `async` in here. Remove the `async` keyword

2021-11-29 04:34 UTC, rusiruavb commented on src/api/services/Application.service.ts
> +    .then(async (applications) => {
No need to have `async` in here. Remove the `async` keyword

2021-11-29 09:44 UTC, AshenWijesingha commented on src/api/services/Application.service.ts
> +    .then(async (application) => {
Done ayye

2021-11-29 09:45 UTC, AshenWijesingha commented on src/api/services/Application.service.ts
> +    .then(async (application) => {
Done ayye

2021-11-29 09:45 UTC, AshenWijesingha commented on src/api/services/Application.service.ts
> +    .then(async (applications) => {
Done ayye

2021-11-29 17:36 UTC, AshenWijesingha commented
requested changes applied

2021-11-29 18:21 UTC, senuravihanjayadeva requested changes

2021-11-29 18:21 UTC, senuravihanjayadeva commented on src/api/services/Application.service.ts
> +    return await ApplicationModel.find({deleteAt: null})
Are u sure is this working

2021-11-29 18:21 UTC, senuravihanjayadeva commented on src/api/services/Application.service.ts
> +    return await ApplicationModel.find({deleteAt: null})
Refer fetchWebinars in Webinar service. Filter data according to that

2021-11-29 18:24 UTC, AshenWijesingha commented on src/api/services/Application.service.ts
> +    return await ApplicationModel.find({deleteAt: null})
OK ayye

2021-11-30 03:38 UTC, rusiruavb requested changes

2021-11-30 03:38 UTC, rusiruavb commented on src/api/services/Application.service.ts
> +        application.deletedAt = new Date();
Add proper indentation for the `if`` condition

2021-11-30 03:38 UTC, rusiruavb commented on src/api/services/Application.service.ts
> +    .then( (application) => {
remove extra space between `then` and `(application)`
`then((application) => {})`

2021-11-30 03:38 UTC, rusiruavb commented on src/api/services/Application.service.ts
> +    .then( (application) => {
remove extra space between `then` and `(application)`
`then((application) => {})`

2021-11-30 17:02 UTC, closed without merging