Fixed the bugs in Top Speaker Services
ms-club-sliit/msclub-backend pull request #63
Opened 2021-11-29 17:39 UTC by ThusharaX

- [x] getTopSpeakers is fixed to prevent getting deleted soft data
- [x] Removed async in then. from insertTopSpeaker, getTopSpeaker, getTopSpeakers
- [x] Checked before assigning attributes in updateTopSpeaker

2021-11-29 17:55 UTC, senuravihanjayadeva commented
CI/CD is failing. Please solve this

2021-11-30 03:01 UTC, senuravihanjayadeva approved these changes

2021-11-30 03:01 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +        if (updateData.socialMediaURLs.facebook) {
What if socialMediaURLs attribute not availble. This should be handle also. Please take a look

2021-11-30 03:01 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +        if (updateData.socialMediaURLs.instagram) {
What if socialMediaURLs attribute not availble. This should be handle also. Please take a look

2021-11-30 03:01 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +        if (updateData.socialMediaURLs.linkedIn) {
What if socialMediaURLs attribute not availble. This should be handle also. Please take a look

2021-11-30 03:01 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +        if (updateData.socialMediaURLs.twitter) {
What if socialMediaURLs attribute not availble. This should be handle also. Please take a look

2021-11-30 03:01 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +        if (updateData.socialMediaURLs.web) {
What if socialMediaURLs attribute not availble. This should be handle also. Please take a look

2021-11-30 03:32 UTC, rusiruavb requested changes

2021-11-30 03:32 UTC, rusiruavb commented on src/api/services/TopSpeaker.service.ts
> +  return await TopSpeakerModel.findById(topSpeakerId)
Before find the speaker check if the speaker deleted or not. If deleted send a message to the controller.
Message - `Speaker is not found`

2021-11-30 03:32 UTC, rusiruavb commented on src/api/services/TopSpeaker.service.ts
> +      return topSpeaker;
Change the name `topSpeaker` to `topSpeakers`, because this function will return an array

2021-11-30 03:32 UTC, rusiruavb commented on src/api/services/TopSpeaker.service.ts
> +        if (updateData.title) {
No need to put `if` conditions for each and every field. Instead try something like this.
```
if (topSpeakerDetails) {
     if (updateData) {
         const speakerUpdateInfo = {
            title: updateData.title,
            description: updateData.description,
            imageUrl: updateData.imageUrl,
            socialMediaURLs: {
               facebook: updateData.socialMediaUrls && updateData.socialMediaURLs.facebook 
                    ? updateData.socialMediaURLs.facebook 
                    : topSpeakerDetails.socialMediaURLs.facebook,
               // Rest of the social media update is same like this.
            }
         };
     }
}
```

2021-11-30 06:36 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +        if (updateData.title) {
For now use if condition. Later we will give a update about this.

2021-11-30 07:44 UTC, ThusharaX commented on src/api/services/TopSpeaker.service.ts
> +        if (updateData.title) {
Ok ayye

2021-11-30 09:32 UTC, ThusharaX commented on src/api/services/TopSpeaker.service.ts
> +      return topSpeaker;
Done ayye ✅

2021-11-30 09:32 UTC, ThusharaX commented on src/api/services/TopSpeaker.service.ts
> +  return await TopSpeakerModel.findById(topSpeakerId)
Done ayye ✅

2021-11-30 11:35 UTC, senuravihanjayadeva requested changes

2021-11-30 11:35 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +      if (topSpeaker) {
here we can use 

if (topSpeaker &&  topSpeaker.deletedAt){
    return topSpeaker;
}else{
    throw new Error("Speaker is not found");
}

@rusiruavb what is your opinion ?

2021-11-30 11:35 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +          topSpeakerDetails.socialMediaURLs = updateData.socialMediaURLs;
remove this line

2021-11-30 11:35 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +          if (updateData.socialMediaURLs.facebook) {
if(updateData.socialMediaURLs && updateData.socialMediaURLs.facebook)

2021-11-30 11:35 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +          if (updateData.socialMediaURLs.instagram) {
if(updateData.socialMediaURLs && updateData.socialMediaURLs.instagram)

2021-11-30 11:35 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +          if (updateData.socialMediaURLs.linkedIn) {
if(updateData.socialMediaURLs && updateData.socialMediaURLs.linkedIn)

2021-11-30 11:35 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +          if (updateData.socialMediaURLs.twitter) {
if(updateData.socialMediaURLs && updateData.socialMediaURLs.twitter)

2021-11-30 11:35 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +          if (updateData.socialMediaURLs.web) {
if(updateData.socialMediaURLs && updateData.socialMediaURLs.web)

2021-11-30 11:35 UTC, senuravihanjayadeva commented on src/api/services/TopSpeaker.service.ts
> +      if (topSpeakerDetails) {
we dont need to use nested if condition. Use following requested changes

2021-11-30 12:40 UTC, ThusharaX commented on src/api/services/TopSpeaker.service.ts
> +      if (topSpeakerDetails) {
Ok ayye 👍

2021-11-30 13:12 UTC, senuravihanjayadeva approved these changes

2021-11-30 13:14 UTC, senuravihanjayadeva approved these changes

2021-11-30 13:14 UTC, merged